blueprint:
  name: Alerte batterie Tado
  description: Alerte batterie faible avec notification
  domain: automation
  author: Beckynet
  homeassistant:
    min_version: 2024.10.0
    
  input:
    battery_sensor:
      name: Capteur de batterie
      selector:
        entity:
          domain:
          - binary_sensor
          device_class:
          - battery
          multiple: true
          reorder: false
          
    notify_target:
      name: Cible de notification
      selector:
        target:
          entity:
            domain: notify
    seuil:
      name: Seuil de batterie (%)
      default: 20
      selector:
        number:
          min: 5
          max: 50
          unit_of_measurement: '%'

  source_url: https://github.com/beckynet/HA_Blueprint/blob/main/batterie_tado.yaml

triggers:
  - trigger: numeric_state
    entity_id: !input battery_sensor
    below: !input seuil
    for: "01:00:00"

conditions:
  - condition: template
    value_template: >
      {{ states(!input.battery_sensor) | int > 0 }}

actions:
  - action: !input notify_target
    data:
      message: >
        ⚠️ Batterie faible détectée sur {{ state_attr(!input.battery_sensor, 'friendly_name') }} ({{ states(!input.battery_sensor) }}%)
mode: single