blueprint:
  name: Reboot HA host
  description: Automated weekly reboot of the entire Home Asistant OS host inspired on work of (by Chef de IT)
  domain: automation
  author: Beckynet
  input:
    reboot_day:
      name: Reboot Day of Week
      description: Pick the best day to reboot, e.g. Monday
      default: tue
      selector:
        select:
          options:
          - mon
          - tue
          - wed
          - thu
          - fri
          - sat
          - sun
          multiple: false
          custom_value: false
          sort: false
    reboot_time:
      name: Reboot time of day
      description: Pick the least busy time for reboot, e.g. 4am
      default: 04:00:00
      selector:
        time: {}
  source_url: https://github.com/beckynet/HA_Blueprint/blob/main/Reboot-HA-weekly.yaml
conditions:
- condition: time
  before: 00:00:00
  after: 00:00:00
  weekday:
  - !input reboot_day
triggers:
- trigger: time
  at: !input reboot_time
actions:
- action: hassio.host_reboot
  data: {}
mode: single